# Used for parallelization by snakemake
cpu_cores: 4

# Used for verbosity, see `logging` from stdlib
log_level: 'DEBUG'

# Choose which records to use from the database for the pipeline
# filter levels: class, order, family, genus, all (no filter)
fasta_filter:
  filter_level: order
  filter_name: Lepidoptera


# File paths
file_paths:
  bold_input: "resources/BOLD/BOLD_Public.08-Nov-2024.tsv"
  raw_sequences: "resources/raw_sequences"
  bold_output: "results/BOLD/BOLD_subset.tsv"
  qiime2_output: "results/qiime2"
  blast_output: "results/blast"

# Dataset name for QIIME2 artifacts
dataset_name: "example_dataset"

# Blast parameters
blast_params:
  max_evalue: 1e-5
  n_threads: 6

# Denoising parametersv
denoise_method: dada2
dada2_params:
  trunc_len: 150
  trim_left: 13
  max_ee: 2
  trunc_q: 2
  chimera_method: consensus
  min_fold_parent_over_abundance: 1
  n_threads: 1

deblur_params:
  trim_length: 150
  left_trim_len: 0
  min_reads: 10
  min_size: 2
  jobs_to_start: 1
  hashed_feature_ids: true